Add files via upload
Patagonian-IUPA/programacion-web-1-dom-1 pull request #3
Opened 2020-12-15 01:36 UTC by Arcaytus

2021-03-03 11:12 UTC, reduardo7 requested changes

2021-03-03 11:12 UTC, reduardo7 commented on ejercicios.js
> +const nodo = template.cloneNode (true);
Creas un `template`, y luego lo clonas, pero no lo usas.

- El `cloneNode` se usa cuando un nodo/elemento ya se encuentra presente en el documento.
- El `template` tal vez debería hacer referencia al HTML, donde creaste un elemento `<template id="myTemplate"` pero no lo usas luego.

2021-03-03 11:12 UTC, reduardo7 commented on ejercicios.js
> +    const li = document.createElement ('li');
Formatear el código de acuerdo a lo aprendido en el trabajo práctico https://github.com/Patagonian-IUPA/try-catch.

2021-03-04 12:59 UTC, reduardo7 commented on ejercicios.js
> +    const li = document.createElement ('li');
No se deja un espacio antes de abrir el `(` en un llamado a la función.
```suggestion
    const li = document.createElement('li');

```

2021-03-04 16:01 UTC, Arcaytus commented on ejercicios.js
> +    const li = document.createElement ('li');
Muchas gracias por la corrección. Ya corregí eso

2021-03-04 16:21 UTC, reduardo7 requested changes

2021-03-04 16:21 UTC, reduardo7 commented on ejercicios.js
> +}
Indentar correctamente el código.

2021-03-04 16:21 UTC, reduardo7 commented on ejercicios.js
> +    console.log ('Error. list element could not be created');
No se deja un espacio antes de abrir el llamado a la función `(`.
```suggestion
    console.log('Error. list element could not be created');

```

2021-03-04 16:21 UTC, reduardo7 commented on ejercicios.js
> +    for (i = 0; i <= 50; i++) {
Declarar variable `i`.
```suggestion
    for (let i = 0; i <= 50; i++) {

```

2021-03-04 16:39 UTC, Arcaytus commented on ejercicios.js
> +}
Cambio realizado.

2021-03-06 16:01 UTC, reduardo7 requested changes

2021-03-06 16:01 UTC, reduardo7 commented on ejercicios.js
> +    console.log ('Finally');
No se deja un espacio antes de abrir el llamado a la función `(`.
```suggestion
    console.log('Finally');

```

2021-03-07 17:57 UTC, reduardo7 approved these changes

2021-03-07 17:58 UTC, closed without merging