Van los ejercicios de práctica sobre el DOM!
Patagonian-IUPA/programacion-web-1-dom-1 pull request #4
Opened 2021-02-10 23:53 UTC by aldocape

Hice comentarios de casi todas las líneas del código js para que se entienda mejor

2021-03-03 11:08 UTC, reduardo7 requested changes

2021-03-03 11:08 UTC, reduardo7 commented on src/ejercicios.js
> +    nodo = elem.cloneNode(true);
Ya estaba clonado en la línea 22. Solo deberías clonarlo una vez.

2021-03-03 11:08 UTC, reduardo7 commented on src/ejercicios.js
> +const elem = tt.content.querySelector('li');
Sugerencia: Usar nombres de variables claros. `elem` no hace referencia a un `li` o `item`.

2021-03-03 20:00 UTC, aldocape commented on src/ejercicios.js
> +    nodo = elem.cloneNode(true);
Listo Edu! Dejé solamente en cloneNode que está adentro de la iteración

2021-03-03 20:01 UTC, aldocape commented on src/ejercicios.js
> +const elem = tt.content.querySelector('li');
Modifiqué el nombre de la variable por uno que identifique mejor el elemento

2021-03-04 13:02 UTC, reduardo7 approved these changes
Excelente!

2021-03-04 13:02 UTC, closed without merging