Ejercicios del DOM resueltos
Patagonian-IUPA/programacion-web-1-dom-1 pull request #5
Opened 2021-02-17 00:45 UTC by lamaolo

2021-03-03 11:03 UTC, reduardo7 requested changes

2021-03-03 11:03 UTC, reduardo7 commented on src/ejercicios.js
> +  listItem.innerText = i;
Creas `listItem`, pero luego no lo usas. Deberías agregarlo al `body` en algún lado.

2021-03-03 11:03 UTC, reduardo7 commented on src/ejercicios.js
> +  unorderedList.appendChild(nodo);
Clonas el nodo, pero no lo modificas. Tal vez aquí debes inyectar tu `listItem`.

2021-03-06 18:38 UTC, lamaolo commented
Hola, ahi mande otro push intentando solucionar esas observaciones. En este caso ahora no creo una constante `listItem` sino que modifico el innerText del `<li>` usando directamente la función `getElementById`, luego ahora si clono el template con el `<li>` con el innerText modificado en el `ul` creado previamente.

2021-03-07 17:47 UTC, reduardo7 approved these changes
Excelente!

2021-03-07 17:47 UTC, closed without merging